# Generated by Django 5.2.17 on 2026-09-19 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DischargeCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mother_name', models.CharField(max_length=64)),
                ('baby_name', models.CharField(max_length=64)),
                ('planned_discharge_at', models.DateTimeField()),
                ('path', models.CharField(blank=True, choices=[('early', '提前离馆返家'), ('transfer', '转往其他机构'), ('nanny_home', '月嫂上门继续服务')], default='', max_length=16)),
                ('transfer_status', models.CharField(choices=[('not_set', '未设置交接路径'), ('pending', '待接收方确认'), ('acked', '接收方已确认，责任已转移')], default='not_set', max_length=16)),
                ('target_name', models.CharField(blank=True, default='', max_length=128)),
                ('target_contact', models.CharField(blank=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'discharge_case',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('role', models.CharField(choices=[('nanny', '月嫂'), ('nutritionist', '营养师'), ('coordinator', '出馆服务专员'), ('receiver', '接收机构人员'), ('family', '家属')], max_length=16)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('organization', models.CharField(blank=True, max_length=128)),
            ],
            options={
                'db_table': 'staff',
            },
        ),
        migrations.CreateModel(
            name='CareEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=8)),
                ('category', models.CharField(choices=[('night_observation', '月嫂夜间观察'), ('diet_advice', '营养师饮食建议'), ('supply_note', '婴儿用品注意事项'), ('followup_task', '返家待办'), ('contact_record', '后续联系记录')], max_length=20)),
                ('content', models.TextField()),
                ('occurred_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', '待确认'), ('confirmed', '已确认')], default='pending', max_length=10)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='handoff.dischargecase')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='confirmed_events', to='handoff.staff')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_events', to='handoff.staff')),
            ],
            options={
                'db_table': 'care_event',
            },
        ),
        migrations.CreateModel(
            name='AuthorizedContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('relation', models.CharField(max_length=32)),
                ('channel', models.CharField(max_length=128)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='handoff.dischargecase')),
            ],
            options={
                'db_table': 'authorized_contact',
            },
        ),
        migrations.CreateModel(
            name='HandoffPacket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('mother', '产妇'), ('baby', '婴儿')], max_length=8)),
                ('version', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('superseded', '已被新版本替代')], default='draft', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packets', to='handoff.dischargecase')),
            ],
            options={
                'db_table': 'handoff_packet',
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivered_at', models.DateTimeField(auto_now_add=True)),
                ('viewed_at', models.DateTimeField(blank=True, null=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='handoff.authorizedcontact')),
                ('packet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='handoff.handoffpacket')),
            ],
            options={
                'db_table': 'delivery',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_version', models.PositiveIntegerField()),
                ('message', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='handoff.authorizedcontact')),
                ('packet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='handoff.handoffpacket')),
            ],
            options={
                'db_table': 'notification',
            },
        ),
        migrations.CreateModel(
            name='PacketSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('summary', '返家摘要'), ('todo', '待办事项'), ('supply', '用品说明'), ('contact', '后续联系记录')], max_length=10)),
                ('content', models.TextField(blank=True, default='')),
                ('state', models.CharField(choices=[('draft', '待确认'), ('confirmed', '专业人员已确认'), ('pending_data', '暂无已确认事实-待处理')], default='draft', max_length=14)),
                ('packet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='handoff.handoffpacket')),
                ('source_events', models.ManyToManyField(related_name='in_sections', to='handoff.careevent')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='handoff.staff')),
            ],
            options={
                'db_table': 'packet_section',
            },
        ),
        migrations.CreateModel(
            name='Anomaly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('block', '阻断'), ('pending', '待处理')], max_length=8)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('open', '未闭环'), ('closed', '已闭环')], default='open', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('resolution', models.TextField(blank=True, default='')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='handoff.dischargecase')),
                ('packet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='handoff.handoffpacket')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='handoff.packetsection')),
            ],
            options={
                'db_table': 'anomaly',
            },
        ),
        migrations.CreateModel(
            name='SectionConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature', models.CharField(max_length=128)),
                ('confirmed_at', models.DateTimeField(auto_now_add=True)),
                ('section', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='confirmation', to='handoff.packetsection')),
                ('confirmer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='handoff.staff')),
            ],
            options={
                'db_table': 'section_confirmation',
            },
        ),
        migrations.CreateModel(
            name='VersionChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('packet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='handoff.handoffpacket')),
            ],
            options={
                'db_table': 'version_change',
            },
        ),
        migrations.AddConstraint(
            model_name='handoffpacket',
            constraint=models.UniqueConstraint(fields=('case', 'subject', 'version'), name='uq_packet_version'),
        ),
        migrations.AddConstraint(
            model_name='delivery',
            constraint=models.UniqueConstraint(fields=('packet', 'contact'), name='uq_delivery'),
        ),
        migrations.AddConstraint(
            model_name='packetsection',
            constraint=models.UniqueConstraint(fields=('packet', 'kind', 'responsible'), name='uq_section_owner'),
        ),
        migrations.AddIndex(
            model_name='careevent',
            index=models.Index(fields=['case', 'subject', 'category'], name='care_event_case_id_0c8f62_idx'),
        ),
    ]
