# Generated by Django 5.2.17 on 2026-09-19 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_name', models.CharField(max_length=100, verbose_name='家庭称呼')),
                ('mother_name', models.CharField(max_length=100, verbose_name='产妇姓名')),
                ('baby_name', models.CharField(max_length=100, verbose_name='婴儿称呼')),
                ('expected_discharge_at', models.DateTimeField(verbose_name='预计离馆时间')),
                ('actual_discharge_at', models.DateTimeField(blank=True, null=True, verbose_name='实际离馆时间')),
                ('status', models.CharField(choices=[('active', '在馆'), ('discharged', '已离馆')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('matron', '月嫂'), ('nutritionist', '营养师'), ('nurse', '护士'), ('coordinator', '服务专员')], max_length=20)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AuthorizedContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('relation', models.CharField(max_length=50)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('is_primary', models.BooleanField(default=False)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='handover.case')),
            ],
        ),
        migrations.CreateModel(
            name='ContactChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('kind', models.CharField(default='phone', max_length=20)),
                ('value', models.CharField(max_length=200)),
                ('hours', models.CharField(blank=True, default='', max_length=100)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_channels', to='handover.case')),
            ],
        ),
        migrations.CreateModel(
            name='FollowUpPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('mother', '产妇'), ('baby', '婴儿')], max_length=10)),
                ('purpose', models.CharField(max_length=200)),
                ('channel', models.CharField(default='phone', max_length=50)),
                ('offset_days', models.IntegerField(help_text='相对离馆时间的天数偏移')),
                ('scheduled_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('scheduled', '已排期'), ('done', '已完成'), ('cancelled', '已取消')], default='scheduled', max_length=20)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='handover.case')),
            ],
        ),
        migrations.CreateModel(
            name='Handover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path_type', models.CharField(choices=[('early_discharge', '提前离馆'), ('transfer_facility', '转往其他机构'), ('home_service', '月嫂上门服务')], max_length=30)),
                ('status', models.CharField(choices=[('initiated', '待接收方确认'), ('receiver_confirmed', '接收方已确认'), ('cancelled', '已取消')], default='initiated', max_length=30)),
                ('receiver_name', models.CharField(max_length=100)),
                ('receiver_org', models.CharField(blank=True, default='', max_length=200)),
                ('receiver_contact', models.CharField(blank=True, default='', max_length=100)),
                ('service_address', models.CharField(blank=True, default='', max_length=300)),
                ('scheduled_at', models.DateTimeField()),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('receiver_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handovers', to='handover.case')),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_handovers', to='handover.professional')),
                ('matron', models.ForeignKey(blank=True, help_text='月嫂上门服务时指定的月嫂', null=True, on_delete=django.db.models.deletion.SET_NULL, to='handover.professional')),
            ],
        ),
        migrations.CreateModel(
            name='Anomaly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('mother', '产妇'), ('baby', '婴儿')], max_length=10)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('blocking', '阻断'), ('advisory', '提示')], max_length=20)),
                ('status', models.CharField(choices=[('open', '未闭环'), ('closed', '已闭环')], default='open', max_length=20)),
                ('resolution', models.TextField(blank=True, default='')),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='handover.case')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_anomalies', to='handover.professional')),
                ('raised_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raised_anomalies', to='handover.professional')),
            ],
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('mother', '产妇'), ('baby', '婴儿')], max_length=10)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='handover.case')),
            ],
            options={
                'unique_together': {('case', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='SummaryVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_no', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('superseded', '已废止')], default='draft', max_length=20)),
                ('change_note', models.TextField(blank=True, default='', verbose_name='更正说明')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='handover.professional')),
                ('summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='handover.summary')),
            ],
            options={
                'ordering': ['-version_no'],
                'unique_together': {('summary', 'version_no')},
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('correction_notice', '更正通知'), ('discharge_changed', '离馆时间变更'), ('handover_update', '交接进展')], max_length=30)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='handover.case')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='handover.authorizedcontact')),
                ('version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='handover.summaryversion')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SupplyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('mother', '产妇'), ('baby', '婴儿')], max_length=10)),
                ('name', models.CharField(max_length=200)),
                ('instruction', models.TextField()),
                ('caution', models.TextField(blank=True, default='')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplies', to='handover.case')),
            ],
        ),
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('mother', '产妇'), ('baby', '婴儿')], max_length=10)),
                ('category', models.CharField(choices=[('night_observation', '夜间观察'), ('nutrition', '饮食建议'), ('supply', '用品注意'), ('vital', '体征记录'), ('other', '其他')], max_length=30)),
                ('content', models.TextField()),
                ('occurred_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', '待确认'), ('confirmed', '已确认'), ('retracted', '已撤回')], default='pending', max_length=20)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='handover.case')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='handover.professional')),
            ],
            options={
                'ordering': ['occurred_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TodoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('mother', '产妇'), ('baby', '婴儿')], max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('detail', models.TextField(blank=True, default='')),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', '待完成'), ('done', '已完成'), ('cancelled', '已取消')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todos', to='handover.case')),
            ],
        ),
        migrations.CreateModel(
            name='SummarySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('night_care', '夜间照护'), ('nutrition', '饮食建议'), ('supplies', '用品说明'), ('todos', '待办事项'), ('contacts', '联系与随访'), ('anomalies', '待处理异常'), ('handover', '交接安排')], max_length=20)),
                ('required_role', models.CharField(blank=True, choices=[('matron', '月嫂'), ('nutritionist', '营养师'), ('nurse', '护士'), ('coordinator', '服务专员')], help_text='为空的章节由系统生成，无需签署', max_length=20, null=True)),
                ('content', models.JSONField(default=dict)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('signed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='handover.professional')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='handover.summaryversion')),
            ],
            options={
                'unique_together': {('version', 'category')},
            },
        ),
        migrations.CreateModel(
            name='DeliveryReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivered_at', models.DateTimeField()),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='handover.authorizedcontact')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='handover.summaryversion')),
            ],
            options={
                'unique_together': {('version', 'contact')},
            },
        ),
        migrations.CreateModel(
            name='SummaryView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='handover.authorizedcontact')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='handover.summaryversion')),
            ],
            options={
                'unique_together': {('version', 'contact')},
            },
        ),
    ]
